#@title JUST UPLOAD:
TARGET_PATH = input("PASTE TARGET PATH HERE\n") # PASTE TARGET PATH HERE
LINK_DOWNLOAD = input("PASTE LINK DOWNLOAD HERE\n") # PASTE LINK DOWNLOAD HERE
 
import os
os.chdir(TARGET_PATH)
!wget -c {LINK_DOWNLOAD} --no-check-certificate
